### GET - Sales for a specific person
GET http://localhost:4004/odata/v4/service/getSalesForPerson(email='liandrocruz@kpmg.com')

### GET - List all users
GET http://localhost:4004/odata/v4/service/getUsers

### GET - List all approvers
GET http://localhost:4004/odata/v4/service/aprovadores

### GET - List all Materials
GET http://localhost:4004/odata/v4/service/artigos

### GET - List all SalesItems
GET http://localhost:4004/odata/v4/service/salesItems

### GET - List all Materials
GET http://localhost:4004/odata/v4/service/sales

---
### create People
POST http://localhost:4004/odata/v4/service/create_salesorder
Content-Type: application/json

{
  "sales": {
    "email_vendor": "bernadettefernandes@kpmg.com",
    "email_comprador": "liandrocruz@kpmg.com",
    "items": [
      {
        "material": "4b361b8b-fef2-46cd-8a03-cfe57da618b7",
        "qtd": 1
      }
    ]
  }
}

### create People
POST http://localhost:4004/odata/v4/service/createUserInSAP
Content-Type: application/json

{
  "email": "Emanuelm@kpmg.com",
  "userType": "approver"
}

###Criar aprovadores
POST http://localhost:4004/odata/v4/service/aprovadores
Content-Type: application/json

{
  "approver": "liandrocruz1@kpmg.com",
  "vendor": "rjjpereira1@kpmg.com"
}


###Criar aprovadores
POST http://localhost:4004/odata/v4/service/updateStatus
Content-Type: application/json

{
  "id": "71",
  "status": "Aceite"
}