### read People
GET http://localhost:4004/odata/v4/service/aprovadores('romer')

### create People
POST http://localhost:4004/odata/v4/service/create_salesorder
Content-Type: application/json

{
  "sales": {
    "email_vendor": "romeritomendes",
    "email_comprador": "comprador@example.com",
    "items": [
      {
        "material": "teste",
        "qtd": 1
      }
    ]
  }
}
